### ISSUE TITLE
error when viewing stored message

### ISSUE THREAD

**Issue by mvoelz** [jackjoe/mailgun_logger#33]
when viewing some mails i get "Something went wrong"

web_1  | 13:18:29.959 [info] GET /events/1838/stored_message
web_1  | 13:18:30.170 [info] Sent 500 in 210ms
web_1  | 13:18:30.170 [error] #PID<0.8130.0> running MailgunLoggerWeb.Endpoint (connection #PID<0.8129.0>, stream id 1) terminated
web_1  | Server: servername:80 (http)
web_1  | Request: GET /events/1838/stored_message
web_1  | ** (exit) an exception was raised:
web_1  |     ** (FunctionClauseError) no function clause matching in String.contains?/2
web_1  |         (elixir 1.15.7) lib/string.ex:2538: String.contains?(nil, "text/plain")
web_1  |         (mailgun_logger 2312.4.0) lib/mailgun/events.ex:73: Mailgun.Events.get_stored_message_content/1
web_1  |         (mailgun_logger 2312.4.0) lib/mailgun_logger_web/controllers/event_controller.ex:31: MailgunLoggerWeb.EventController.stored_message/2
web_1  |         (mailgun_logger 2312.4.0) lib/mailgun_logger_web/controllers/event_controller.ex:1: MailgunLoggerWeb.EventController.action/2
web_1  |         (mailgun_logger 2312.4.0) lib/mailgun_logger_web/controllers/event_controller.ex:1: MailgunLoggerWeb.EventController.phoenix_controller_pipeline/2
web_1  |         (phoenix 1.7.7) lib/phoenix/router.ex:430: Phoenix.Router.__call__/5
web_1  |         (mailgun_logger 2312.4.0) deps/plug/lib/plug/error_handler.ex:80: MailgunLoggerWeb.Router.call/2
web_1  |         (mailgun_logger 2312.4.0) lib/mailgun_logger_web/endpoint.ex:1: MailgunLoggerWeb.Endpoint.plug_builder_call/2

the stored message is just plain txt nothing fancy, other mails work fine.

**Comment by jeroenbourgois** [comment]
I made a change recently how to show the stored message. I'll have a look, but it will probably be after the holidays.

**Comment by jeroenbourgois** [comment]
Also, in the future here and in other projects: can you wrap logs in backticks or the code icon in the toolbar? Makes it more readable.

**Comment by jeroenbourgois** [comment]
@mvoelz can you show the contents of the event? The content type value in the msg part appears to be empty. I added a check for it but am still interested in how it was nil.

**Comment by jeroenbourgois** [comment]
Fixed in latest version (2312.5.0)

**Comment by mvoelz** [comment]
Hi,
I don't see that error in the logs anymore, but the email message is still not rendering properly (empty page).

this is the json file from s3:
```
{
    "Date": "Sun, 28 Jan 2024 14:47:15 +0100 (CET)",
    "Delivered-To": "root@localhost",
    "From": "munin@monitor.localdomain (munin application user)",
    "Message-Id": "<20240128134715.8282C65E6E@monitor>",
    "Received": "by monitor (Postfix, from userid 108) id 8282C65E6E; Sun, 28 Jan 2024 14:47:15 +0100 (CET)",
    "Subject": "Munin-notification for home :: tower.home :: ELK :: Auditbeat Count",
    "To": "<root@localhost>",
    "X-Mailer": "mail (GNU Mailutils 2.99.98)",
    "attachments": [],
    "body-plain": "home :: tower.home :: Auditbeat Count\r\n\tOKs: count last 5 mins is 14765.00.\r\n\r\n",
    "content-id-map": {},
    "from": "munin@monitor.localdomain (munin application user)",
    "message-headers": [
        [
            "Received",
            "by monitor (Postfix) id 83A6F5FDCD; Sun, 28 Jan 2024 14:47:15 +0100 (CET)"
        ],
        [
            "Received",
            "by monitor (Postfix, from userid 108) id 8282C65E6E; Sun, 28 Jan 2024 14:47:15 +0100 (CET)"
        ],
        [
            "Delivered-To",
            "root@localhost"
        ],
        [
            "Subject",
            "Munin-notification for home :: tower.home :: ELK :: Auditbeat Count"
        ],
        [
            "To",
            "<root@localhost>"
        ],
        [
            "X-Mailer",
            "mail (GNU Mailutils 2.99.98)"
        ],
        [
            "Message-Id",
            "<20240128134715.8282C65E6E@monitor>"
        ],
        [
            "Date",
            "Sun, 28 Jan 2024 14:47:15 +0100 (CET)"
        ],
        [
            "From",
            "munin@monitor.localdomain (munin application user)"
        ]
    ],
    "recipients": "email@gmail.com",
    "sender": "munin@monitor.localdomain",
    "stripped-html": "<p>home :: tower.home :: Auditbeat Count\r\n\tOKs: count last 5 mins is 14765.00.</p>",
    "stripped-signature": "",
    "stripped-text": "home :: tower.home :: Auditbeat Count\r\n\tOKs: count last 5 mins is 14765.00.",
    "subject": "Munin-notification for home :: tower.home :: ELK :: Auditbeat Count"
}
```

**Comment by jeroenbourgois** [comment]
@mvoelz sry for the low response rate, I'll try to have a look this week.

**Comment by jeroenbourgois** [comment]
@mvoelz If you can submit a PR I will be happy to look into it!
